export const NormalActions = [
  'RESET_ERROR',
  'SET_EXCLUDE_UNANSWERED',

  'ADD_QUESTION_TO_LIST',
  'EDIT_QUESTION_IN_LIST',
  'REMOVE_QUESTION_FROM_LIST',

  'ADD_CALENDAR_TO_LIST',
  'REMOVE_CALENDAR_FROM_LIST',

  'ADD_CATEGORY_TO_LIST',
  'EDIT_CATEGORY_IN_LIST',
  'REMOVE_CATEGORY_FROM_LIST',

  'ADD_TAG_TO_LIST',
  'EDIT_TAG_IN_LIST',
  'REMOVE_TAG_FROM_LIST',
];

export const RequestActions = [
  'GET_LOCAL_TOKEN',
  'TEST',
  'LOGIN',
  'LOGOUT',
  'REGISTER',
  'RESET_PASSWORD',
  
  'GET_PROFILE',
  'UPLOAD_PROFILE',
  'CHANGE_PASSWORD',
  'RESEND_VERIFY_EMAIL',

  'GET_LEARNING_HISTORY',
  'RESET_LEARNING_HISTORY',
  'GET_NEXT_QUESTION',
  'SAVE_ANSWER',

  'LIST_QUESTION',
  'UPLOAD_QUESTION',
  'REMOVE_QUESTION',

  'LIST_CALENDAR',
  'UPLOAD_CALENDAR',
  'REMOVE_CALENDAR',

  'LIST_CATEGORY',
  'UPLOAD_CATEGORY',
  'REMOVE_CATEGORY',

  'LIST_TAG',
  'UPLOAD_TAG',
  'REMOVE_TAG',
];
